"""initial migration

Revision ID: 20e21ac27427
Revises: 
Create Date: 2025-09-20 22:55:30.550641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20e21ac27427'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('phone', sa.String(length=13), nullable=False),
    sa.Column('email', sa.String(length=30), nullable=False),
    sa.Column('reason', sa.String(length=200), nullable=False),
    sa.Column('date', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('no'),
    sa.UniqueConstraint('reason')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact')
    # ### end Alembic commands ###
